# Generated by Django 5.0 on 2024-06-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='taskTable',
        ),
    ]
