# Generated by Django 5.0 on 2025-03-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagementApp', '0002_producttable_delete_tasktable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=20)),
            ],
        ),
    ]
