# Generated by Django 5.0 on 2025-03-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagementApp', '0003_categorytable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_address', models.TextField()),
                ('c_email', models.EmailField(max_length=254, unique=True)),
                ('c_phone', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=255)),
                ('s_address', models.TextField()),
                ('s_email', models.EmailField(max_length=254, unique=True)),
                ('s_phone', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='productTable',
        ),
    ]
